on:
  push:
    paths:
      - ".github/workflows/azure-function-build-deploy.yml"
      - "AzureFunction/**"
  release:
    types: [created]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./AzureFunction
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./AzureFunction
      - name: Copy Release Files To Artifacts Directory
        run: |
         mkdir -p artifactsdirectory         
         cp -r ./AzureFunction/bin/Release/netcoreapp3.1/bin ./artifactsdirectory
         cp -r ./AzureFunction/bin/Release/netcoreapp3.1/funcnsgflowlogblobtrigger ./artifactsdirectory
         cp -r ./AzureFunction/bin/Release/netcoreapp3.1/host.json ./artifactsdirectory

         functionAppName=$(cat ./Deploy/parameters.bicep.json | jq -r ".parameters.functionName.value")
         echo "::set-env name=FUNCTIONAPPNAME::$functionAppName"

      - uses: azure/login@v1
        name: Azure cli login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: $FUNCTIONAPPNAME
          package: 'artifactsdirectory'