on:
  push:
    branches: [ master, RahulS/feature/build_pipeline  ]
  pull_request:
    branches: [ master,RahulS/feature/build_pipeline ]
  release:
    types: [created]

jobs:
  build-and-deploy:
    name: Plan and Deploy Infra
    runs-on: ubuntu-18.04
    environment: dev
    steps:
    # Checkout Repository
      - uses: actions/checkout@v2

    # Login to Azure using Service Principal
      - uses: azure/login@v1
        name: Azure cli login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

     # Deploy Bicep file
      - name: Plan and check infra changes
        run: |
          cat ./Deploy/parameters.bicep.json| jq -r ".parameters.resourceGroupName.value"
          az deployment group what-if --resource-group rg-dev-nsgflowlogs \
          --template-file .\Deploy\template.bicep --parameters .\Deploy\parameters.bicep.json
      