on:
  push:
    branches: [ master, RahulS/feature/build_pipeline  ]
    paths:
      - ".github/workflows/azure-function-build-deploy.yml"
      - "AzureFunction/**"
  pull_request:
    branches: [ master,RahulS/feature/build_pipeline ]
    paths:
      - ".github/workflows/azure-function-build-deploy.yml"
      - "AzureFunction/**"
  release:
    types: [created]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./AzureFunction
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./AzureFunction
      - name: Copy Release Files To Artifacts Directory
        run: |
         mkdir -p artifactsdirectory         
         cp -r ./AzureFunction/bin/Release/netcoreapp3.1/bin ./artifactsdirectory
         cp -r ./AzureFunction/bin/Release/netcoreapp3.1/funcnsgflowlogblobtrigger ./artifactsdirectory
         cp -r ./AzureFunction/bin/Release/netcoreapp3.1/host.json ./artifactsdirectory
      - uses: actions/upload-artifact@v2
        name: Azure Function Artifact
        with:
          name: artifact-function-blobtrigger
          path: artifactsdirectory

      - uses: azure/login@v1
        name: Azure cli login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az resource list -g rg-dev-nsgflowlogs --query "[].name" -o tsv
        name: Test Azure Login